name: "Android Build Action"
description: "Build Android APK using devbox with parameterized configuration"

inputs:
  build-type:
    description: "Build type: preview or production"
    required: true
    type: string
  devbox-config:
    description: "Path to devbox configuration directory"
    required: true
    type: string
  artifact-name:
    description: "Name for output APK artifact"
    required: true
    type: string

outputs:
  apk-path:
    description: "Path to built APK file"
    value: ${{ steps.build.outputs.apk-path }}
  build-successful:
    description: "Whether build completed successfully"
    value: ${{ steps.build.outputs.success }}

runs:
  using: composite
  steps:
    - name: Setup development environment
      uses: ./.github/actions/setup-dev-environment
      with:
        devbox-config: ${{ inputs.devbox-config }}

    - name: Build APK
      shell: bash
      working-directory: devbox/${{ inputs.devbox-config }}
      run: |
        if [ "${{ inputs.build-type }}" = "production" ]; then
          # Use parameterized build script: build.sh production build_production.apk
          ../../scripts/build.sh production build_production.apk
          echo "apk-path=./build_production.apk" >> $GITHUB_OUTPUT
        else
          # Use parameterized build script: build.sh preview build_preview.apk  
          ../../scripts/build.sh preview build_preview.apk
          echo "apk-path=./build_preview.apk" >> $GITHUB_OUTPUT
        fi
        echo "success=true" >> $GITHUB_OUTPUT
      id: build

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.build.outputs.apk-path }}
        retention-days: 30
