name: Build Production APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

permissions:
  contents: write

jobs:
  validate-main:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4
      - name: 🛠 Setup development environment
        uses: ./.github/actions/setup-dev-environment
        with:
          devbox-config: minimal
      - name: Quick validation
        working-directory: devbox/minimal
        run: |
          devbox run test
          devbox run typecheck
          devbox run lint

  build:
    runs-on: ubuntu-latest
    environment: Dev
    needs: validate-main
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4
      - name: Build Production APK
        uses: ./.github/actions/android-build
        with:
          build-type: production
          devbox-config: android-build
          artifact-name: production-release-apk
        id: build-production
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Production build from commit ${{ github.sha }}
            Build successful: ${{ steps.build-production.outputs.build-successful }}

            Changes: ${{ github.event.head_commit.message }}
          files: ${{ steps.build-production.outputs.apk-path }}
