name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-preview:
    name: Cleanup Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v4

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: ðŸ”¥ Delete Firebase Hosting Channel
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STRENGTH_ASSISTANT_DEV }}' > /tmp/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json
          
          # Install Firebase CLI
          npm install -g firebase-tools
          
          # Delete the channel
          firebase hosting:channel:delete pr-${{ github.event.number }} --project strength-assistant-dev --force --non-interactive
          
          # Clean up credentials
          rm /tmp/firebase-service-account.json
        continue-on-error: true

      - name: ðŸ“ Update PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            const comment = `## ðŸ”— Preview Deployment
            
            ~~**Preview URL**: https://pr-${pr.number}--strength-assistant-dev.web.app~~
            
            **âœ… Preview environment has been cleaned up** (PR closed)`;
            
            // Find existing preview comment
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
            });
            
            const existingComment = comments.data.find(
              comment => comment.body.includes('## ðŸ”— Preview Deployment')
            );
            
            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: comment,
              });
            }
        continue-on-error: true