name: "Maestro Test Action"
description: "Run Maestro integration tests using devbox with parameterized configuration"

inputs:
  apk-path:
    description: "Path to APK file to test"
    required: true
    type: string
  test-environment:
    description: "Test environment: integration or production"
    required: true
    type: string
  skip-data-cleanup:
    description: "Skip data cleanup (SKIP_DATA_CLEANUP environment variable)"
    required: false
    type: boolean
    default: false
  devbox-config:
    description: "Path to devbox test configuration directory"
    required: true
    type: string

outputs:
  success:
    description: "Boolean indicating if tests passed (true/false)"
    value: ${{ steps.test.outputs.success }}
  exit-code:
    description: "Raw exit code from test execution"
    value: ${{ steps.test.outputs.exit-code }}
  test-duration:
    description: "Test execution time in seconds"
    value: ${{ steps.test.outputs.test-duration }}
  artifacts-path:
    description: "Path to debug artifacts directory"
    value: ${{ steps.test.outputs.artifacts-path }}

runs:
  using: composite
  steps:
    - name: Enable KVM for Android emulator
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Setup testing environment
      uses: ./.github/actions/setup-dev-environment
      with:
        devbox-config: ${{ inputs.devbox-config }}

    - name: Run Maestro Tests
      shell: bash
      working-directory: devbox/${{ inputs.devbox-config }}
      env:
        SKIP_DATA_CLEANUP: ${{ inputs.skip-data-cleanup }}
        TEST_ENVIRONMENT: ${{ inputs.test-environment }}
      run: |
        echo "🔄 Running integration tests with APK: ${{ inputs.apk-path }}"

        # Record start time for duration calculation
        START_TIME=$(date +%s)

        # Use devbox run to execute with proper environment
        devbox run -- ../../scripts/integration_test_android.sh "${{ inputs.apk-path }}"
        TEST_EXIT_CODE=$?

        # Calculate test duration
        END_TIME=$(date +%s)
        TEST_DURATION=$((END_TIME - START_TIME))

        echo "success=$([ $TEST_EXIT_CODE -eq 0 ] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
        echo "exit-code=$TEST_EXIT_CODE" >> $GITHUB_OUTPUT
        echo "test-duration=$TEST_DURATION" >> $GITHUB_OUTPUT
        echo "artifacts-path=./maestro-debug-output" >> $GITHUB_OUTPUT

        # Add debug artifact location reporting for failures
        if [ $TEST_EXIT_CODE -ne 0 ]; then
          echo "ERROR: Integration tests failed with exit code $TEST_EXIT_CODE"
          echo "Debug artifacts available at: ./maestro-debug-output"
          echo "Failure details: Check test logs and screenshots in debug artifacts"
        fi

        exit $TEST_EXIT_CODE
      id: test

    - name: Upload test result artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.test-environment }}-test-results
        path: |
          maestro-debug-output/
          *.png
          *.xml
          devbox/${{ inputs.devbox-config }}/maestro-debug-output/
        retention-days: 14
