name: Create Production Builds

on:
  push:
    branches: ['main']

jobs:
  build_android_preview:
    type: build
    params:
      platform: android
      profile: preview
      android: # Add this section for Android specific settings
        buildType: apk # Specify to build an APK

  build_android_development:
    type: build
    params:
      platform: android
      profile: development
      android: # Add this section for Android specific settings
        buildType: apk # Specify to build an APK
