name: Create Production Builds

on:
  push:
    branches: ['main']

jobs:
  build_android_preview:
    type: build
    params:
      platform: android
      profile: preview

  build_android_development:
    type: build
    params:
      platform: android
      profile: development
